filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

alias(
    name = "anise_cpp_tests",
    actual = "//:anise_cpp_tests",
    visibility = ["//visibility:public"],
)
