// automatically generated by the FlatBuffers compiler, do not modify



use crate::time_generated::*;
use crate::common_generated::*;
use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod anise {

  use crate::time_generated::*;
  use crate::common_generated::*;
  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod orientation {

  use crate::time_generated::*;
  use crate::common_generated::*;
  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_INTERPOLATOR: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_INTERPOLATOR: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_INTERPOLATOR: [Interpolator; 3] = [
  Interpolator::NONE,
  Interpolator::equal_time_steps,
  Interpolator::unequal_time_steps,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Interpolator(pub u8);
#[allow(non_upper_case_globals)]
impl Interpolator {
  pub const NONE: Self = Self(0);
  pub const equal_time_steps: Self = Self(1);
  pub const unequal_time_steps: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::equal_time_steps,
    Self::unequal_time_steps,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::equal_time_steps => Some("equal_time_steps"),
      Self::unequal_time_steps => Some("unequal_time_steps"),
      _ => None,
    }
  }
}
impl std::fmt::Debug for Interpolator {
  fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Interpolator {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe {
      flatbuffers::read_scalar_at::<u8>(buf, loc)
    };
    Self(b)
  }
}

impl flatbuffers::Push for Interpolator {
    type Output = Interpolator;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for Interpolator {
  #[inline]
  fn to_little_endian(self) -> Self {
    let b = u8::to_le(self.0);
    Self(b)
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(self) -> Self {
    let b = u8::from_le(self.0);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Interpolator {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Interpolator {}
pub struct InterpolatorUnionTableOffset {}

pub enum OrientationCoefficientsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct OrientationCoefficients<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for OrientationCoefficients<'a> {
    type Inner = OrientationCoefficients<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> OrientationCoefficients<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        OrientationCoefficients { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args OrientationCoefficientsArgs<'args>) -> flatbuffers::WIPOffset<OrientationCoefficients<'bldr>> {
      let mut builder = OrientationCoefficientsBuilder::new(_fbb);
      builder.add_usable_end_time_offset_cs(args.usable_end_time_offset_cs);
      builder.add_usable_start_time_offset_cs(args.usable_start_time_offset_cs);
      if let Some(x) = args.cov_rate_z_rate_z { builder.add_cov_rate_z_rate_z(x); }
      if let Some(x) = args.cov_rate_z_rate_y { builder.add_cov_rate_z_rate_y(x); }
      if let Some(x) = args.cov_rate_z_rate_x { builder.add_cov_rate_z_rate_x(x); }
      if let Some(x) = args.cov_rate_z_quat_z { builder.add_cov_rate_z_quat_z(x); }
      if let Some(x) = args.cov_rate_z_quat_y { builder.add_cov_rate_z_quat_y(x); }
      if let Some(x) = args.cov_rate_z_quat_x { builder.add_cov_rate_z_quat_x(x); }
      if let Some(x) = args.cov_rate_z_quat_w { builder.add_cov_rate_z_quat_w(x); }
      if let Some(x) = args.cov_rate_y_rate_y { builder.add_cov_rate_y_rate_y(x); }
      if let Some(x) = args.cov_rate_y_rate_x { builder.add_cov_rate_y_rate_x(x); }
      if let Some(x) = args.cov_rate_y_quat_z { builder.add_cov_rate_y_quat_z(x); }
      if let Some(x) = args.cov_rate_y_quat_y { builder.add_cov_rate_y_quat_y(x); }
      if let Some(x) = args.cov_rate_y_quat_x { builder.add_cov_rate_y_quat_x(x); }
      if let Some(x) = args.cov_rate_y_quat_w { builder.add_cov_rate_y_quat_w(x); }
      if let Some(x) = args.cov_rate_x_rate_x { builder.add_cov_rate_x_rate_x(x); }
      if let Some(x) = args.cov_rate_x_quat_z { builder.add_cov_rate_x_quat_z(x); }
      if let Some(x) = args.cov_rate_x_quat_y { builder.add_cov_rate_x_quat_y(x); }
      if let Some(x) = args.cov_rate_x_quat_x { builder.add_cov_rate_x_quat_x(x); }
      if let Some(x) = args.cov_rate_x_quat_w { builder.add_cov_rate_x_quat_w(x); }
      if let Some(x) = args.cov_quat_z_quat_z { builder.add_cov_quat_z_quat_z(x); }
      if let Some(x) = args.cov_quat_z_quat_y { builder.add_cov_quat_z_quat_y(x); }
      if let Some(x) = args.cov_quat_z_quat_x { builder.add_cov_quat_z_quat_x(x); }
      if let Some(x) = args.cov_quat_z_quat_w { builder.add_cov_quat_z_quat_w(x); }
      if let Some(x) = args.cov_quat_y_quat_y { builder.add_cov_quat_y_quat_y(x); }
      if let Some(x) = args.cov_quat_y_quat_x { builder.add_cov_quat_y_quat_x(x); }
      if let Some(x) = args.cov_quat_y_quat_w { builder.add_cov_quat_y_quat_w(x); }
      if let Some(x) = args.cov_quat_x_quat_x { builder.add_cov_quat_x_quat_x(x); }
      if let Some(x) = args.cov_quat_x_quat_w { builder.add_cov_quat_x_quat_w(x); }
      if let Some(x) = args.cov_quat_w_quat_w { builder.add_cov_quat_w_quat_w(x); }
      if let Some(x) = args.rate_z { builder.add_rate_z(x); }
      if let Some(x) = args.rate_y { builder.add_rate_y(x); }
      if let Some(x) = args.rate_x { builder.add_rate_x(x); }
      if let Some(x) = args.quat_z { builder.add_quat_z(x); }
      if let Some(x) = args.quat_y { builder.add_quat_y(x); }
      if let Some(x) = args.quat_x { builder.add_quat_x(x); }
      if let Some(x) = args.quat_w { builder.add_quat_w(x); }
      builder.finish()
    }

    pub const VT_USABLE_START_TIME_OFFSET_CS: flatbuffers::VOffsetT = 4;
    pub const VT_USABLE_END_TIME_OFFSET_CS: flatbuffers::VOffsetT = 6;
    pub const VT_QUAT_W: flatbuffers::VOffsetT = 8;
    pub const VT_QUAT_X: flatbuffers::VOffsetT = 10;
    pub const VT_QUAT_Y: flatbuffers::VOffsetT = 12;
    pub const VT_QUAT_Z: flatbuffers::VOffsetT = 14;
    pub const VT_RATE_X: flatbuffers::VOffsetT = 16;
    pub const VT_RATE_Y: flatbuffers::VOffsetT = 18;
    pub const VT_RATE_Z: flatbuffers::VOffsetT = 20;
    pub const VT_COV_QUAT_W_QUAT_W: flatbuffers::VOffsetT = 22;
    pub const VT_COV_QUAT_X_QUAT_W: flatbuffers::VOffsetT = 24;
    pub const VT_COV_QUAT_X_QUAT_X: flatbuffers::VOffsetT = 26;
    pub const VT_COV_QUAT_Y_QUAT_W: flatbuffers::VOffsetT = 28;
    pub const VT_COV_QUAT_Y_QUAT_X: flatbuffers::VOffsetT = 30;
    pub const VT_COV_QUAT_Y_QUAT_Y: flatbuffers::VOffsetT = 32;
    pub const VT_COV_QUAT_Z_QUAT_W: flatbuffers::VOffsetT = 34;
    pub const VT_COV_QUAT_Z_QUAT_X: flatbuffers::VOffsetT = 36;
    pub const VT_COV_QUAT_Z_QUAT_Y: flatbuffers::VOffsetT = 38;
    pub const VT_COV_QUAT_Z_QUAT_Z: flatbuffers::VOffsetT = 40;
    pub const VT_COV_RATE_X_QUAT_W: flatbuffers::VOffsetT = 42;
    pub const VT_COV_RATE_X_QUAT_X: flatbuffers::VOffsetT = 44;
    pub const VT_COV_RATE_X_QUAT_Y: flatbuffers::VOffsetT = 46;
    pub const VT_COV_RATE_X_QUAT_Z: flatbuffers::VOffsetT = 48;
    pub const VT_COV_RATE_X_RATE_X: flatbuffers::VOffsetT = 50;
    pub const VT_COV_RATE_Y_QUAT_W: flatbuffers::VOffsetT = 52;
    pub const VT_COV_RATE_Y_QUAT_X: flatbuffers::VOffsetT = 54;
    pub const VT_COV_RATE_Y_QUAT_Y: flatbuffers::VOffsetT = 56;
    pub const VT_COV_RATE_Y_QUAT_Z: flatbuffers::VOffsetT = 58;
    pub const VT_COV_RATE_Y_RATE_X: flatbuffers::VOffsetT = 60;
    pub const VT_COV_RATE_Y_RATE_Y: flatbuffers::VOffsetT = 62;
    pub const VT_COV_RATE_Z_QUAT_W: flatbuffers::VOffsetT = 64;
    pub const VT_COV_RATE_Z_QUAT_X: flatbuffers::VOffsetT = 66;
    pub const VT_COV_RATE_Z_QUAT_Y: flatbuffers::VOffsetT = 68;
    pub const VT_COV_RATE_Z_QUAT_Z: flatbuffers::VOffsetT = 70;
    pub const VT_COV_RATE_Z_RATE_X: flatbuffers::VOffsetT = 72;
    pub const VT_COV_RATE_Z_RATE_Y: flatbuffers::VOffsetT = 74;
    pub const VT_COV_RATE_Z_RATE_Z: flatbuffers::VOffsetT = 76;

  #[inline]
  pub fn usable_start_time_offset_cs(&self) -> f64 {
    self._tab.get::<f64>(OrientationCoefficients::VT_USABLE_START_TIME_OFFSET_CS, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn usable_end_time_offset_cs(&self) -> f64 {
    self._tab.get::<f64>(OrientationCoefficients::VT_USABLE_END_TIME_OFFSET_CS, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_QUAT_W, None)
  }
  #[inline]
  pub fn quat_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_QUAT_X, None)
  }
  #[inline]
  pub fn quat_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_QUAT_Y, None)
  }
  #[inline]
  pub fn quat_z(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_QUAT_Z, None)
  }
  #[inline]
  pub fn rate_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_RATE_X, None)
  }
  #[inline]
  pub fn rate_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_RATE_Y, None)
  }
  #[inline]
  pub fn rate_z(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_RATE_Z, None)
  }
  #[inline]
  pub fn cov_quat_w_quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_W_QUAT_W, None)
  }
  #[inline]
  pub fn cov_quat_x_quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_X_QUAT_W, None)
  }
  #[inline]
  pub fn cov_quat_x_quat_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_X_QUAT_X, None)
  }
  #[inline]
  pub fn cov_quat_y_quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_Y_QUAT_W, None)
  }
  #[inline]
  pub fn cov_quat_y_quat_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_Y_QUAT_X, None)
  }
  #[inline]
  pub fn cov_quat_y_quat_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_Y_QUAT_Y, None)
  }
  #[inline]
  pub fn cov_quat_z_quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_W, None)
  }
  #[inline]
  pub fn cov_quat_z_quat_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_X, None)
  }
  #[inline]
  pub fn cov_quat_z_quat_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_Y, None)
  }
  #[inline]
  pub fn cov_quat_z_quat_z(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_Z, None)
  }
  #[inline]
  pub fn cov_rate_x_quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_W, None)
  }
  #[inline]
  pub fn cov_rate_x_quat_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_X, None)
  }
  #[inline]
  pub fn cov_rate_x_quat_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_Y, None)
  }
  #[inline]
  pub fn cov_rate_x_quat_z(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_Z, None)
  }
  #[inline]
  pub fn cov_rate_x_rate_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_X_RATE_X, None)
  }
  #[inline]
  pub fn cov_rate_y_quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_W, None)
  }
  #[inline]
  pub fn cov_rate_y_quat_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_X, None)
  }
  #[inline]
  pub fn cov_rate_y_quat_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_Y, None)
  }
  #[inline]
  pub fn cov_rate_y_quat_z(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_Z, None)
  }
  #[inline]
  pub fn cov_rate_y_rate_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Y_RATE_X, None)
  }
  #[inline]
  pub fn cov_rate_y_rate_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Y_RATE_Y, None)
  }
  #[inline]
  pub fn cov_rate_z_quat_w(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_W, None)
  }
  #[inline]
  pub fn cov_rate_z_quat_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_X, None)
  }
  #[inline]
  pub fn cov_rate_z_quat_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_Y, None)
  }
  #[inline]
  pub fn cov_rate_z_quat_z(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_Z, None)
  }
  #[inline]
  pub fn cov_rate_z_rate_x(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Z_RATE_X, None)
  }
  #[inline]
  pub fn cov_rate_z_rate_y(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Z_RATE_Y, None)
  }
  #[inline]
  pub fn cov_rate_z_rate_z(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(OrientationCoefficients::VT_COV_RATE_Z_RATE_Z, None)
  }
}

impl flatbuffers::Verifiable for OrientationCoefficients<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<f64>(&"usable_start_time_offset_cs", Self::VT_USABLE_START_TIME_OFFSET_CS, false)?
     .visit_field::<f64>(&"usable_end_time_offset_cs", Self::VT_USABLE_END_TIME_OFFSET_CS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"quat_w", Self::VT_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"quat_x", Self::VT_QUAT_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"quat_y", Self::VT_QUAT_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"quat_z", Self::VT_QUAT_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"rate_x", Self::VT_RATE_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"rate_y", Self::VT_RATE_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"rate_z", Self::VT_RATE_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_w_quat_w", Self::VT_COV_QUAT_W_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_x_quat_w", Self::VT_COV_QUAT_X_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_x_quat_x", Self::VT_COV_QUAT_X_QUAT_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_y_quat_w", Self::VT_COV_QUAT_Y_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_y_quat_x", Self::VT_COV_QUAT_Y_QUAT_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_y_quat_y", Self::VT_COV_QUAT_Y_QUAT_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_z_quat_w", Self::VT_COV_QUAT_Z_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_z_quat_x", Self::VT_COV_QUAT_Z_QUAT_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_z_quat_y", Self::VT_COV_QUAT_Z_QUAT_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_quat_z_quat_z", Self::VT_COV_QUAT_Z_QUAT_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_x_quat_w", Self::VT_COV_RATE_X_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_x_quat_x", Self::VT_COV_RATE_X_QUAT_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_x_quat_y", Self::VT_COV_RATE_X_QUAT_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_x_quat_z", Self::VT_COV_RATE_X_QUAT_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_x_rate_x", Self::VT_COV_RATE_X_RATE_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_y_quat_w", Self::VT_COV_RATE_Y_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_y_quat_x", Self::VT_COV_RATE_Y_QUAT_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_y_quat_y", Self::VT_COV_RATE_Y_QUAT_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_y_quat_z", Self::VT_COV_RATE_Y_QUAT_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_y_rate_x", Self::VT_COV_RATE_Y_RATE_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_y_rate_y", Self::VT_COV_RATE_Y_RATE_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_z_quat_w", Self::VT_COV_RATE_Z_QUAT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_z_quat_x", Self::VT_COV_RATE_Z_QUAT_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_z_quat_y", Self::VT_COV_RATE_Z_QUAT_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_z_quat_z", Self::VT_COV_RATE_Z_QUAT_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_z_rate_x", Self::VT_COV_RATE_Z_RATE_X, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_z_rate_y", Self::VT_COV_RATE_Z_RATE_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>(&"cov_rate_z_rate_z", Self::VT_COV_RATE_Z_RATE_Z, false)?
     .finish();
    Ok(())
  }
}
pub struct OrientationCoefficientsArgs<'a> {
    pub usable_start_time_offset_cs: f64,
    pub usable_end_time_offset_cs: f64,
    pub quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub quat_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub quat_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub quat_z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub rate_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub rate_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub rate_z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_w_quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_x_quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_x_quat_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_y_quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_y_quat_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_y_quat_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_z_quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_z_quat_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_z_quat_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_quat_z_quat_z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_x_quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_x_quat_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_x_quat_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_x_quat_z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_x_rate_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_y_quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_y_quat_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_y_quat_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_y_quat_z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_y_rate_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_y_rate_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_z_quat_w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_z_quat_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_z_quat_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_z_quat_z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_z_rate_x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_z_rate_y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub cov_rate_z_rate_z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
}
impl<'a> Default for OrientationCoefficientsArgs<'a> {
    #[inline]
    fn default() -> Self {
        OrientationCoefficientsArgs {
            usable_start_time_offset_cs: 0.0,
            usable_end_time_offset_cs: 0.0,
            quat_w: None,
            quat_x: None,
            quat_y: None,
            quat_z: None,
            rate_x: None,
            rate_y: None,
            rate_z: None,
            cov_quat_w_quat_w: None,
            cov_quat_x_quat_w: None,
            cov_quat_x_quat_x: None,
            cov_quat_y_quat_w: None,
            cov_quat_y_quat_x: None,
            cov_quat_y_quat_y: None,
            cov_quat_z_quat_w: None,
            cov_quat_z_quat_x: None,
            cov_quat_z_quat_y: None,
            cov_quat_z_quat_z: None,
            cov_rate_x_quat_w: None,
            cov_rate_x_quat_x: None,
            cov_rate_x_quat_y: None,
            cov_rate_x_quat_z: None,
            cov_rate_x_rate_x: None,
            cov_rate_y_quat_w: None,
            cov_rate_y_quat_x: None,
            cov_rate_y_quat_y: None,
            cov_rate_y_quat_z: None,
            cov_rate_y_rate_x: None,
            cov_rate_y_rate_y: None,
            cov_rate_z_quat_w: None,
            cov_rate_z_quat_x: None,
            cov_rate_z_quat_y: None,
            cov_rate_z_quat_z: None,
            cov_rate_z_rate_x: None,
            cov_rate_z_rate_y: None,
            cov_rate_z_rate_z: None,
        }
    }
}
pub struct OrientationCoefficientsBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> OrientationCoefficientsBuilder<'a, 'b> {
  #[inline]
  pub fn add_usable_start_time_offset_cs(&mut self, usable_start_time_offset_cs: f64) {
    self.fbb_.push_slot::<f64>(OrientationCoefficients::VT_USABLE_START_TIME_OFFSET_CS, usable_start_time_offset_cs, 0.0);
  }
  #[inline]
  pub fn add_usable_end_time_offset_cs(&mut self, usable_end_time_offset_cs: f64) {
    self.fbb_.push_slot::<f64>(OrientationCoefficients::VT_USABLE_END_TIME_OFFSET_CS, usable_end_time_offset_cs, 0.0);
  }
  #[inline]
  pub fn add_quat_w(&mut self, quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_QUAT_W, quat_w);
  }
  #[inline]
  pub fn add_quat_x(&mut self, quat_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_QUAT_X, quat_x);
  }
  #[inline]
  pub fn add_quat_y(&mut self, quat_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_QUAT_Y, quat_y);
  }
  #[inline]
  pub fn add_quat_z(&mut self, quat_z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_QUAT_Z, quat_z);
  }
  #[inline]
  pub fn add_rate_x(&mut self, rate_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_RATE_X, rate_x);
  }
  #[inline]
  pub fn add_rate_y(&mut self, rate_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_RATE_Y, rate_y);
  }
  #[inline]
  pub fn add_rate_z(&mut self, rate_z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_RATE_Z, rate_z);
  }
  #[inline]
  pub fn add_cov_quat_w_quat_w(&mut self, cov_quat_w_quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_W_QUAT_W, cov_quat_w_quat_w);
  }
  #[inline]
  pub fn add_cov_quat_x_quat_w(&mut self, cov_quat_x_quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_X_QUAT_W, cov_quat_x_quat_w);
  }
  #[inline]
  pub fn add_cov_quat_x_quat_x(&mut self, cov_quat_x_quat_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_X_QUAT_X, cov_quat_x_quat_x);
  }
  #[inline]
  pub fn add_cov_quat_y_quat_w(&mut self, cov_quat_y_quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_Y_QUAT_W, cov_quat_y_quat_w);
  }
  #[inline]
  pub fn add_cov_quat_y_quat_x(&mut self, cov_quat_y_quat_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_Y_QUAT_X, cov_quat_y_quat_x);
  }
  #[inline]
  pub fn add_cov_quat_y_quat_y(&mut self, cov_quat_y_quat_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_Y_QUAT_Y, cov_quat_y_quat_y);
  }
  #[inline]
  pub fn add_cov_quat_z_quat_w(&mut self, cov_quat_z_quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_W, cov_quat_z_quat_w);
  }
  #[inline]
  pub fn add_cov_quat_z_quat_x(&mut self, cov_quat_z_quat_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_X, cov_quat_z_quat_x);
  }
  #[inline]
  pub fn add_cov_quat_z_quat_y(&mut self, cov_quat_z_quat_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_Y, cov_quat_z_quat_y);
  }
  #[inline]
  pub fn add_cov_quat_z_quat_z(&mut self, cov_quat_z_quat_z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_QUAT_Z_QUAT_Z, cov_quat_z_quat_z);
  }
  #[inline]
  pub fn add_cov_rate_x_quat_w(&mut self, cov_rate_x_quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_W, cov_rate_x_quat_w);
  }
  #[inline]
  pub fn add_cov_rate_x_quat_x(&mut self, cov_rate_x_quat_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_X, cov_rate_x_quat_x);
  }
  #[inline]
  pub fn add_cov_rate_x_quat_y(&mut self, cov_rate_x_quat_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_Y, cov_rate_x_quat_y);
  }
  #[inline]
  pub fn add_cov_rate_x_quat_z(&mut self, cov_rate_x_quat_z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_X_QUAT_Z, cov_rate_x_quat_z);
  }
  #[inline]
  pub fn add_cov_rate_x_rate_x(&mut self, cov_rate_x_rate_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_X_RATE_X, cov_rate_x_rate_x);
  }
  #[inline]
  pub fn add_cov_rate_y_quat_w(&mut self, cov_rate_y_quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_W, cov_rate_y_quat_w);
  }
  #[inline]
  pub fn add_cov_rate_y_quat_x(&mut self, cov_rate_y_quat_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_X, cov_rate_y_quat_x);
  }
  #[inline]
  pub fn add_cov_rate_y_quat_y(&mut self, cov_rate_y_quat_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_Y, cov_rate_y_quat_y);
  }
  #[inline]
  pub fn add_cov_rate_y_quat_z(&mut self, cov_rate_y_quat_z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Y_QUAT_Z, cov_rate_y_quat_z);
  }
  #[inline]
  pub fn add_cov_rate_y_rate_x(&mut self, cov_rate_y_rate_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Y_RATE_X, cov_rate_y_rate_x);
  }
  #[inline]
  pub fn add_cov_rate_y_rate_y(&mut self, cov_rate_y_rate_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Y_RATE_Y, cov_rate_y_rate_y);
  }
  #[inline]
  pub fn add_cov_rate_z_quat_w(&mut self, cov_rate_z_quat_w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_W, cov_rate_z_quat_w);
  }
  #[inline]
  pub fn add_cov_rate_z_quat_x(&mut self, cov_rate_z_quat_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_X, cov_rate_z_quat_x);
  }
  #[inline]
  pub fn add_cov_rate_z_quat_y(&mut self, cov_rate_z_quat_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_Y, cov_rate_z_quat_y);
  }
  #[inline]
  pub fn add_cov_rate_z_quat_z(&mut self, cov_rate_z_quat_z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Z_QUAT_Z, cov_rate_z_quat_z);
  }
  #[inline]
  pub fn add_cov_rate_z_rate_x(&mut self, cov_rate_z_rate_x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Z_RATE_X, cov_rate_z_rate_x);
  }
  #[inline]
  pub fn add_cov_rate_z_rate_y(&mut self, cov_rate_z_rate_y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Z_RATE_Y, cov_rate_z_rate_y);
  }
  #[inline]
  pub fn add_cov_rate_z_rate_z(&mut self, cov_rate_z_rate_z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OrientationCoefficients::VT_COV_RATE_Z_RATE_Z, cov_rate_z_rate_z);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> OrientationCoefficientsBuilder<'a, 'b> {
    let start = _fbb.start_table();
    OrientationCoefficientsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<OrientationCoefficients<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl std::fmt::Debug for OrientationCoefficients<'_> {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let mut ds = f.debug_struct("OrientationCoefficients");
      ds.field("usable_start_time_offset_cs", &self.usable_start_time_offset_cs());
      ds.field("usable_end_time_offset_cs", &self.usable_end_time_offset_cs());
      ds.field("quat_w", &self.quat_w());
      ds.field("quat_x", &self.quat_x());
      ds.field("quat_y", &self.quat_y());
      ds.field("quat_z", &self.quat_z());
      ds.field("rate_x", &self.rate_x());
      ds.field("rate_y", &self.rate_y());
      ds.field("rate_z", &self.rate_z());
      ds.field("cov_quat_w_quat_w", &self.cov_quat_w_quat_w());
      ds.field("cov_quat_x_quat_w", &self.cov_quat_x_quat_w());
      ds.field("cov_quat_x_quat_x", &self.cov_quat_x_quat_x());
      ds.field("cov_quat_y_quat_w", &self.cov_quat_y_quat_w());
      ds.field("cov_quat_y_quat_x", &self.cov_quat_y_quat_x());
      ds.field("cov_quat_y_quat_y", &self.cov_quat_y_quat_y());
      ds.field("cov_quat_z_quat_w", &self.cov_quat_z_quat_w());
      ds.field("cov_quat_z_quat_x", &self.cov_quat_z_quat_x());
      ds.field("cov_quat_z_quat_y", &self.cov_quat_z_quat_y());
      ds.field("cov_quat_z_quat_z", &self.cov_quat_z_quat_z());
      ds.field("cov_rate_x_quat_w", &self.cov_rate_x_quat_w());
      ds.field("cov_rate_x_quat_x", &self.cov_rate_x_quat_x());
      ds.field("cov_rate_x_quat_y", &self.cov_rate_x_quat_y());
      ds.field("cov_rate_x_quat_z", &self.cov_rate_x_quat_z());
      ds.field("cov_rate_x_rate_x", &self.cov_rate_x_rate_x());
      ds.field("cov_rate_y_quat_w", &self.cov_rate_y_quat_w());
      ds.field("cov_rate_y_quat_x", &self.cov_rate_y_quat_x());
      ds.field("cov_rate_y_quat_y", &self.cov_rate_y_quat_y());
      ds.field("cov_rate_y_quat_z", &self.cov_rate_y_quat_z());
      ds.field("cov_rate_y_rate_x", &self.cov_rate_y_rate_x());
      ds.field("cov_rate_y_rate_y", &self.cov_rate_y_rate_y());
      ds.field("cov_rate_z_quat_w", &self.cov_rate_z_quat_w());
      ds.field("cov_rate_z_quat_x", &self.cov_rate_z_quat_x());
      ds.field("cov_rate_z_quat_y", &self.cov_rate_z_quat_y());
      ds.field("cov_rate_z_quat_z", &self.cov_rate_z_quat_z());
      ds.field("cov_rate_z_rate_x", &self.cov_rate_z_rate_x());
      ds.field("cov_rate_z_rate_y", &self.cov_rate_z_rate_y());
      ds.field("cov_rate_z_rate_z", &self.cov_rate_z_rate_z());
      ds.finish()
  }
}
pub enum EqualTimeStepsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EqualTimeSteps<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EqualTimeSteps<'a> {
    type Inner = EqualTimeSteps<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> EqualTimeSteps<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        EqualTimeSteps { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args EqualTimeStepsArgs<'args>) -> flatbuffers::WIPOffset<EqualTimeSteps<'bldr>> {
      let mut builder = EqualTimeStepsBuilder::new(_fbb);
      builder.add_spline_duration_s(args.spline_duration_s);
      if let Some(x) = args.coefficient_data { builder.add_coefficient_data(x); }
      builder.finish()
    }

    pub const VT_SPLINE_DURATION_S: flatbuffers::VOffsetT = 4;
    pub const VT_COEFFICIENT_DATA: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn spline_duration_s(&self) -> f64 {
    self._tab.get::<f64>(EqualTimeSteps::VT_SPLINE_DURATION_S, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn coefficient_data(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<OrientationCoefficients<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<OrientationCoefficients>>>>(EqualTimeSteps::VT_COEFFICIENT_DATA, None)
  }
}

impl flatbuffers::Verifiable for EqualTimeSteps<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<f64>(&"spline_duration_s", Self::VT_SPLINE_DURATION_S, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<OrientationCoefficients>>>>(&"coefficient_data", Self::VT_COEFFICIENT_DATA, false)?
     .finish();
    Ok(())
  }
}
pub struct EqualTimeStepsArgs<'a> {
    pub spline_duration_s: f64,
    pub coefficient_data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<OrientationCoefficients<'a>>>>>,
}
impl<'a> Default for EqualTimeStepsArgs<'a> {
    #[inline]
    fn default() -> Self {
        EqualTimeStepsArgs {
            spline_duration_s: 0.0,
            coefficient_data: None,
        }
    }
}
pub struct EqualTimeStepsBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> EqualTimeStepsBuilder<'a, 'b> {
  #[inline]
  pub fn add_spline_duration_s(&mut self, spline_duration_s: f64) {
    self.fbb_.push_slot::<f64>(EqualTimeSteps::VT_SPLINE_DURATION_S, spline_duration_s, 0.0);
  }
  #[inline]
  pub fn add_coefficient_data(&mut self, coefficient_data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<OrientationCoefficients<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EqualTimeSteps::VT_COEFFICIENT_DATA, coefficient_data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> EqualTimeStepsBuilder<'a, 'b> {
    let start = _fbb.start_table();
    EqualTimeStepsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EqualTimeSteps<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl std::fmt::Debug for EqualTimeSteps<'_> {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let mut ds = f.debug_struct("EqualTimeSteps");
      ds.field("spline_duration_s", &self.spline_duration_s());
      ds.field("coefficient_data", &self.coefficient_data());
      ds.finish()
  }
}
pub enum UnequalTimeStepsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UnequalTimeSteps<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for UnequalTimeSteps<'a> {
    type Inner = UnequalTimeSteps<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> UnequalTimeSteps<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        UnequalTimeSteps { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args UnequalTimeStepsArgs<'args>) -> flatbuffers::WIPOffset<UnequalTimeSteps<'bldr>> {
      let mut builder = UnequalTimeStepsBuilder::new(_fbb);
      builder.add_time_normalization_max(args.time_normalization_max);
      builder.add_time_normalization_min(args.time_normalization_min);
      if let Some(x) = args.coefficient_data { builder.add_coefficient_data(x); }
      if let Some(x) = args.spline_time_index_cs { builder.add_spline_time_index_cs(x); }
      builder.finish()
    }

    pub const VT_SPLINE_TIME_INDEX_CS: flatbuffers::VOffsetT = 4;
    pub const VT_COEFFICIENT_DATA: flatbuffers::VOffsetT = 6;
    pub const VT_TIME_NORMALIZATION_MIN: flatbuffers::VOffsetT = 8;
    pub const VT_TIME_NORMALIZATION_MAX: flatbuffers::VOffsetT = 10;

  #[inline]
  pub fn spline_time_index_cs(&self) -> Option<flatbuffers::Vector<'a, i64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i64>>>(UnequalTimeSteps::VT_SPLINE_TIME_INDEX_CS, None)
  }
  #[inline]
  pub fn coefficient_data(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<OrientationCoefficients<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<OrientationCoefficients>>>>(UnequalTimeSteps::VT_COEFFICIENT_DATA, None)
  }
  #[inline]
  pub fn time_normalization_min(&self) -> f64 {
    self._tab.get::<f64>(UnequalTimeSteps::VT_TIME_NORMALIZATION_MIN, Some(-1.0)).unwrap()
  }
  #[inline]
  pub fn time_normalization_max(&self) -> f64 {
    self._tab.get::<f64>(UnequalTimeSteps::VT_TIME_NORMALIZATION_MAX, Some(+1.0)).unwrap()
  }
}

impl flatbuffers::Verifiable for UnequalTimeSteps<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i64>>>(&"spline_time_index_cs", Self::VT_SPLINE_TIME_INDEX_CS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<OrientationCoefficients>>>>(&"coefficient_data", Self::VT_COEFFICIENT_DATA, false)?
     .visit_field::<f64>(&"time_normalization_min", Self::VT_TIME_NORMALIZATION_MIN, false)?
     .visit_field::<f64>(&"time_normalization_max", Self::VT_TIME_NORMALIZATION_MAX, false)?
     .finish();
    Ok(())
  }
}
pub struct UnequalTimeStepsArgs<'a> {
    pub spline_time_index_cs: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i64>>>,
    pub coefficient_data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<OrientationCoefficients<'a>>>>>,
    pub time_normalization_min: f64,
    pub time_normalization_max: f64,
}
impl<'a> Default for UnequalTimeStepsArgs<'a> {
    #[inline]
    fn default() -> Self {
        UnequalTimeStepsArgs {
            spline_time_index_cs: None,
            coefficient_data: None,
            time_normalization_min: -1.0,
            time_normalization_max: +1.0,
        }
    }
}
pub struct UnequalTimeStepsBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> UnequalTimeStepsBuilder<'a, 'b> {
  #[inline]
  pub fn add_spline_time_index_cs(&mut self, spline_time_index_cs: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(UnequalTimeSteps::VT_SPLINE_TIME_INDEX_CS, spline_time_index_cs);
  }
  #[inline]
  pub fn add_coefficient_data(&mut self, coefficient_data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<OrientationCoefficients<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(UnequalTimeSteps::VT_COEFFICIENT_DATA, coefficient_data);
  }
  #[inline]
  pub fn add_time_normalization_min(&mut self, time_normalization_min: f64) {
    self.fbb_.push_slot::<f64>(UnequalTimeSteps::VT_TIME_NORMALIZATION_MIN, time_normalization_min, -1.0);
  }
  #[inline]
  pub fn add_time_normalization_max(&mut self, time_normalization_max: f64) {
    self.fbb_.push_slot::<f64>(UnequalTimeSteps::VT_TIME_NORMALIZATION_MAX, time_normalization_max, +1.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> UnequalTimeStepsBuilder<'a, 'b> {
    let start = _fbb.start_table();
    UnequalTimeStepsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<UnequalTimeSteps<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl std::fmt::Debug for UnequalTimeSteps<'_> {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let mut ds = f.debug_struct("UnequalTimeSteps");
      ds.field("spline_time_index_cs", &self.spline_time_index_cs());
      ds.field("coefficient_data", &self.coefficient_data());
      ds.field("time_normalization_min", &self.time_normalization_min());
      ds.field("time_normalization_max", &self.time_normalization_max());
      ds.finish()
  }
}
pub enum OrientationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Orientation<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Orientation<'a> {
    type Inner = Orientation<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> Orientation<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Orientation { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args OrientationArgs<'args>) -> flatbuffers::WIPOffset<Orientation<'bldr>> {
      let mut builder = OrientationBuilder::new(_fbb);
      if let Some(x) = args.constants { builder.add_constants(x); }
      builder.add_parent_hash(args.parent_hash);
      if let Some(x) = args.interpolator { builder.add_interpolator(x); }
      if let Some(x) = args.start_epoch { builder.add_start_epoch(x); }
      if let Some(x) = args.name { builder.add_name(x); }
      builder.add_interpolator_type(args.interpolator_type);
      builder.add_interpolation_kind(args.interpolation_kind);
      builder.finish()
    }

    pub const VT_NAME: flatbuffers::VOffsetT = 4;
    pub const VT_START_EPOCH: flatbuffers::VOffsetT = 6;
    pub const VT_INTERPOLATION_KIND: flatbuffers::VOffsetT = 8;
    pub const VT_INTERPOLATOR_TYPE: flatbuffers::VOffsetT = 10;
    pub const VT_INTERPOLATOR: flatbuffers::VOffsetT = 12;
    pub const VT_PARENT_HASH: flatbuffers::VOffsetT = 14;
    pub const VT_CONSTANTS: flatbuffers::VOffsetT = 16;

  #[inline]
  pub fn name(&self) -> &'a str {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Orientation::VT_NAME, None).unwrap()
  }
  #[inline]
  pub fn start_epoch(&self) -> &'a super::time::Epoch {
    self._tab.get::<super::time::Epoch>(Orientation::VT_START_EPOCH, None).unwrap()
  }
  #[inline]
  pub fn interpolation_kind(&self) -> super::common::InterpolationKind {
    self._tab.get::<super::common::InterpolationKind>(Orientation::VT_INTERPOLATION_KIND, Some(super::common::InterpolationKind::ChebyshevSeries)).unwrap()
  }
  #[inline]
  pub fn interpolator_type(&self) -> Interpolator {
    self._tab.get::<Interpolator>(Orientation::VT_INTERPOLATOR_TYPE, Some(Interpolator::NONE)).unwrap()
  }
  #[inline]
  pub fn interpolator(&self) -> flatbuffers::Table<'a> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(Orientation::VT_INTERPOLATOR, None).unwrap()
  }
  #[inline]
  pub fn parent_hash(&self) -> i32 {
    self._tab.get::<i32>(Orientation::VT_PARENT_HASH, Some(0)).unwrap()
  }
  #[inline]
  pub fn constants(&self) -> Option<super::common::ConstantMap<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<super::common::ConstantMap>>(Orientation::VT_CONSTANTS, None)
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn interpolator_as_equal_time_steps(&self) -> Option<EqualTimeSteps<'a>> {
    if self.interpolator_type() == Interpolator::equal_time_steps {
      let u = self.interpolator();
      Some(EqualTimeSteps::init_from_table(u))
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn interpolator_as_unequal_time_steps(&self) -> Option<UnequalTimeSteps<'a>> {
    if self.interpolator_type() == Interpolator::unequal_time_steps {
      let u = self.interpolator();
      Some(UnequalTimeSteps::init_from_table(u))
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for Orientation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>(&"name", Self::VT_NAME, true)?
     .visit_field::<super::time::Epoch>(&"start_epoch", Self::VT_START_EPOCH, true)?
     .visit_field::<super::common::InterpolationKind>(&"interpolation_kind", Self::VT_INTERPOLATION_KIND, false)?
     .visit_union::<Interpolator, _>(&"interpolator_type", Self::VT_INTERPOLATOR_TYPE, &"interpolator", Self::VT_INTERPOLATOR, true, |key, v, pos| {
        match key {
          Interpolator::equal_time_steps => v.verify_union_variant::<flatbuffers::ForwardsUOffset<EqualTimeSteps>>("Interpolator::equal_time_steps", pos),
          Interpolator::unequal_time_steps => v.verify_union_variant::<flatbuffers::ForwardsUOffset<UnequalTimeSteps>>("Interpolator::unequal_time_steps", pos),
          _ => Ok(()),
        }
     })?
     .visit_field::<i32>(&"parent_hash", Self::VT_PARENT_HASH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::common::ConstantMap>>(&"constants", Self::VT_CONSTANTS, false)?
     .finish();
    Ok(())
  }
}
pub struct OrientationArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub start_epoch: Option<&'a super::time::Epoch>,
    pub interpolation_kind: super::common::InterpolationKind,
    pub interpolator_type: Interpolator,
    pub interpolator: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
    pub parent_hash: i32,
    pub constants: Option<flatbuffers::WIPOffset<super::common::ConstantMap<'a>>>,
}
impl<'a> Default for OrientationArgs<'a> {
    #[inline]
    fn default() -> Self {
        OrientationArgs {
            name: None, // required field
            start_epoch: None, // required field
            interpolation_kind: super::common::InterpolationKind::ChebyshevSeries,
            interpolator_type: Interpolator::NONE,
            interpolator: None, // required field
            parent_hash: 0,
            constants: None,
        }
    }
}
pub struct OrientationBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> OrientationBuilder<'a, 'b> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Orientation::VT_NAME, name);
  }
  #[inline]
  pub fn add_start_epoch(&mut self, start_epoch: &super::time::Epoch) {
    self.fbb_.push_slot_always::<&super::time::Epoch>(Orientation::VT_START_EPOCH, start_epoch);
  }
  #[inline]
  pub fn add_interpolation_kind(&mut self, interpolation_kind: super::common::InterpolationKind) {
    self.fbb_.push_slot::<super::common::InterpolationKind>(Orientation::VT_INTERPOLATION_KIND, interpolation_kind, super::common::InterpolationKind::ChebyshevSeries);
  }
  #[inline]
  pub fn add_interpolator_type(&mut self, interpolator_type: Interpolator) {
    self.fbb_.push_slot::<Interpolator>(Orientation::VT_INTERPOLATOR_TYPE, interpolator_type, Interpolator::NONE);
  }
  #[inline]
  pub fn add_interpolator(&mut self, interpolator: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Orientation::VT_INTERPOLATOR, interpolator);
  }
  #[inline]
  pub fn add_parent_hash(&mut self, parent_hash: i32) {
    self.fbb_.push_slot::<i32>(Orientation::VT_PARENT_HASH, parent_hash, 0);
  }
  #[inline]
  pub fn add_constants(&mut self, constants: flatbuffers::WIPOffset<super::common::ConstantMap<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::common::ConstantMap>>(Orientation::VT_CONSTANTS, constants);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> OrientationBuilder<'a, 'b> {
    let start = _fbb.start_table();
    OrientationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Orientation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Orientation::VT_NAME,"name");
    self.fbb_.required(o, Orientation::VT_START_EPOCH,"start_epoch");
    self.fbb_.required(o, Orientation::VT_INTERPOLATOR,"interpolator");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl std::fmt::Debug for Orientation<'_> {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let mut ds = f.debug_struct("Orientation");
      ds.field("name", &self.name());
      ds.field("start_epoch", &self.start_epoch());
      ds.field("interpolation_kind", &self.interpolation_kind());
      ds.field("interpolator_type", &self.interpolator_type());
      match self.interpolator_type() {
        Interpolator::equal_time_steps => {
          if let Some(x) = self.interpolator_as_equal_time_steps() {
            ds.field("interpolator", &x)
          } else {
            ds.field("interpolator", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Interpolator::unequal_time_steps => {
          if let Some(x) = self.interpolator_as_unequal_time_steps() {
            ds.field("interpolator", &x)
          } else {
            ds.field("interpolator", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("interpolator", &x)
        },
      };
      ds.field("parent_hash", &self.parent_hash());
      ds.field("constants", &self.constants());
      ds.finish()
  }
}
}  // pub mod Orientation
}  // pub mod Anise

